#pragma once

#ifdef _WIN32
#include <Windows.h>
#endif

#define _USE_MATH_DEFINES
#include <cstddef>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <ranges>
#include <span>
#include <cmath>
#include <vector>
#include <stb_image.h>
#include <stb_image_write.h>
#include <string>
#include <stdexcept>
#include <system_error>
#include <thread>
#include <memory>
#include <queue>
#include <algorithm>
#include <numeric>
#include <list>
#include <iterator>
#include <utility>
#include <unordered_map>
#include <functional>
#include <map>
#include <array>
#include <string_view>
#include <execution>
#include <memory_resource>
#include <glm/mat4x4.hpp>
#include <glm/vec4.hpp>
#include <glm/vec3.hpp>
#include <glm/common.hpp>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtx/euler_angles.hpp>
#include <glm/gtx/rotate_vector.hpp>
#include <proxy/proxy.h>
#include <format>
#include <cuda.h>
#include <cuda_runtime_api.h>
